### ISSUE TITLE
sd_isRembg error

### ISSUE THREAD

**Issue by boricuapab** [nguyenvuducthuy/thuy_b2sd#3]
When I enabled the sd_isRembg, I got this error

Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
PermissionError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x00000202A738B3D0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /danielgatis/rembg/releases/download/v0.0.0/u2net.onnx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202A738B3D0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 121, in execute
    butils.doit(isanim              = b2sd.isRenAnim,
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 384, in doit
    run_sd([currentImgPath],
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 322, in run_sd
    rmbg(sd_out_img)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\b2sd.py", line 215, in rmbg
    output = remove(_input)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\rembg\bg.py", line 133, in remove
    session = new_session("u2net")
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\rembg\session_factory.py", line 51, in new_session
    pooch.retrieve(
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\pooch\core.py", line 240, in retrieve
    stream_download(url, full_path, known_hash, downloader, pooch=None)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\pooch\core.py", line 772, in stream_download
    downloader(url, tmp, pooch)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\pooch\downloaders.py", line 189, in __call__
    response = requests.get(url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\python\lib\site-packages\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /danielgatis/rembg/releases/download/v0.0.0/u2net.onnx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000202A738B3D0>: Failed to establish a new connection: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions'))

**Comment by nguyenvuducthuy** [comment]
look like that is a problem with rembg module, not sure why ...

**Comment by boricuapab** [comment]
Got it working after uninstalling and reinstalling pillow and rembg

![BgRemvA_Thuy_0909](https://user-images.githubusercontent.com/61924816/226815546-c23b2af8-49b7-4465-a187-54ac3af176c9.png)

![BgRemvB_Thuy_0909_rembg](https://user-images.githubusercontent.com/61924816/226815566-150a9cf2-145a-403f-875b-431b714ac214.png)
